<?php
/**
 * generate_pdf.php
 * Fetches topic content from DB and streams a PDF download.
 * Usage: generate_pdf.php?id=TOPIC_ID
 */
ob_start(); // buffer any stray output so FPDF can send headers cleanly
session_start();

if (!isset($_SESSION['user_id'])) {
    header('Location: index.php');
    exit;
}

$topic_id = (int) ($_GET['id'] ?? 0);
if (!$topic_id) {
    die('Invalid topic.');
}

require_once 'php_action/db.php';

$user_id = (int) $_SESSION['user_id'];

// Fetch only this user's topic (security: user_id check)
$stmt = $conn->prepare(
    "SELECT topic_name, ai_response, learned_at
     FROM topics_learned
     WHERE id = ? AND user_id = ?
     LIMIT 1"
);
$stmt->bind_param('ii', $topic_id, $user_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die('Topic not found or access denied.');
}

$row         = $result->fetch_assoc();
$topic_name  = $row['topic_name'];
$ai_response = $row['ai_response'];
$learned_at  = $row['learned_at'];

$stmt->close();
$conn->close();

// ── Strip Markdown to plain text for PDF ─────────────────────────────────────
function stripMarkdown(string $text): string {
    // Remove code blocks
    $text = preg_replace('/```[\s\S]*?```/', '', $text);
    // Remove inline code
    $text = preg_replace('/`[^`]+`/', '', $text);
    // Remove headings markers
    $text = preg_replace('/^#{1,6}\s*/m', '', $text);
    // Remove bold/italic markers
    $text = preg_replace('/\*\*([^*]+)\*\*/', '$1', $text);
    $text = preg_replace('/\*([^*]+)\*/',   '$1', $text);
    $text = preg_replace('/__([^_]+)__/',   '$1', $text);
    $text = preg_replace('/_([^_]+)_/',     '$1', $text);
    // Remove blockquote markers
    $text = preg_replace('/^>\s*/m', '', $text);
    // Remove horizontal rules
    $text = preg_replace('/^[-*_]{3,}\s*$/m', '', $text);
    // Remove links [text](url) → text
    $text = preg_replace('/\[([^\]]+)\]\([^)]+\)/', '$1', $text);
    // Remove images
    $text = preg_replace('/!\[([^\]]*)\]\([^)]+\)/', '', $text);
    // Normalise line endings
    $text = str_replace("\r\n", "\n", $text);
    $text = preg_replace("/\n{3,}/", "\n\n", $text);
    return trim($text);
}

// ── Strip emojis and non-windows-1252 characters ─────────────────────────────
function removeEmojis(string $text): string {
    // Remove all characters outside the Basic Latin + Latin-1 Supplement blocks
    // that windows-1252 can handle (U+0000–U+00FF range essentially)
    return preg_replace('/[^\x00-\xFF]/u', '', $text);
}

function safeIconv(string $text): string {
    $text = removeEmojis($text);
    $result = @iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', $text);
    return ($result === false) ? $text : $result;
}

$plain_text = stripMarkdown($ai_response);

// ── Generate PDF with FPDF ────────────────────────────────────────────────────
// Make sure fpdf.php is in your project. Download from http://www.fpdf.org/
// or: composer require setasign/fpdf  then use vendor/autoload.php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/fpdf.php')) {
    require_once __DIR__ . '/fpdf.php';
} else {
    // Fallback: plain text download if FPDF not installed
    header('Content-Type: text/plain; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . preg_replace('/[^a-z0-9_-]/i', '_', $topic_name) . '.txt"');
    echo "TOPIC: $topic_name\n";
    echo "Studied on: $learned_at\n\n";
    echo $plain_text;
    exit;
}

class StudyPDF extends FPDF {
    public string $topic = '';
    public string $date  = '';

    function Header() {
        // Accent bar
        $this->SetFillColor(99, 102, 241);
        $this->Rect(0, 0, 210, 3, 'F');

        $this->SetFont('Helvetica', 'B', 16);
        $this->SetTextColor(30, 30, 60);
        $this->SetY(10);
        $this->Cell(0, 10, safeIconv($this->topic), 0, 1, 'L');

        $this->SetFont('Helvetica', '', 9);
        $this->SetTextColor(107, 114, 128);
        $this->Cell(0, 6, 'Studied on: ' . $this->date . '   |   Generated by AI Tutor', 0, 1, 'L');

        $this->SetDrawColor(220, 220, 235);
        $this->Line(10, $this->GetY(), 200, $this->GetY());
        $this->Ln(4);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(150, 150, 160);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . ' / {nb}  |  AI Tutor Study Notes', 0, 0, 'C');
    }
}

$pdf = new StudyPDF();
$pdf->topic = $topic_name;
$pdf->date  = date('d M Y', strtotime($learned_at));
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 20);

// Write content in chunks, detecting section headings
$lines = explode("\n", $plain_text);
foreach ($lines as $line) {
    $line = trim($line);
    if ($line === '') {
        $pdf->Ln(3);
        continue;
    }

    // Detect what was a heading (starts with emoji bullet or all caps short line)
    if (mb_strlen($line) < 80 && (
        preg_match('/^[A-Z][A-Z\s:]{5,}$/', $line) ||
        preg_match('/^\p{So}/u', $line)              // starts with emoji
    )) {
        $pdf->SetFont('Helvetica', 'B', 12);
        $pdf->SetTextColor(60, 60, 180);
        $text = safeIconv($line);
        $pdf->MultiCell(0, 7, $text, 0, 'L');
        $pdf->Ln(1);
    } elseif (str_starts_with($line, '- ') || str_starts_with($line, '• ')) {
        $pdf->SetFont('Helvetica', '', 10.5);
        $pdf->SetTextColor(40, 40, 60);
        $bullet = chr(149) . ' ' . ltrim($line, '- •');
        $text = safeIconv($bullet);
        $pdf->SetX(14);
        $pdf->MultiCell(186, 6, $text, 0, 'L');
    } else {
        $pdf->SetFont('Helvetica', '', 10.5);
        $pdf->SetTextColor(40, 40, 60);
        $text = safeIconv($line);
        $pdf->MultiCell(0, 6.5, $text, 0, 'L');
    }
}

$safe_name = preg_replace('/[^a-z0-9_-]/i', '_', $topic_name);
ob_end_clean(); // discard any buffered output before streaming PDF
$pdf->Output('D', $safe_name . '_study_notes.pdf');
exit;